SHAPE = (299, 299, 3)
# SHAPE = (150, 150, 1)
# LEARNING_RATE = 0.0001
# BATCH_SIZE = 16
# EPOCHS = 1
# PRE_TRAIN_EPOCHS = 200
# DO_PRE_TRAIN = False
# DO_TRAIN = True
# DO_VALIDATION = True
# DO_TEST = False
COLOR_MODE = "rgb"
CLASSES = ["index", "resoluties", "respecten", "frontpage"]
